import { OSM_PILOT_POIS } from "./poi-catalog-osm.generated";
import type {
  TripActivityCategory,
  TripActivityEnvironment,
  TripActivityReservation,
  TripWeatherSensitivity,
} from "./activity-intelligence";

export type PoiLocale = "en" | "zh-cn" | "zh-hant";

export interface CuratedPoi {
  readonly id: string;
  readonly cityId: string;
  readonly name: Record<PoiLocale, string>;
  readonly latitude: number;
  readonly longitude: number;
  readonly category: TripActivityCategory;
  readonly environment: TripActivityEnvironment;
  readonly weatherSensitivity: ReadonlyArray<TripWeatherSensitivity>;
  readonly typicalDurationMinutes: number;
  readonly reservation: TripActivityReservation;
  readonly recommendedWindow: "morning" | "afternoon" | "evening" | "any";
  readonly provenance: "curated-v1" | "openstreetmap-v1";
  readonly sourceRef?: string;
}

type PoiSeed = Omit<CuratedPoi, "provenance" | "weatherSensitivity"> & {
  readonly weatherSensitivity?: ReadonlyArray<TripWeatherSensitivity>;
};

function sensitivity(environment: TripActivityEnvironment): ReadonlyArray<TripWeatherSensitivity> {
  if (environment === "indoor") return [];
  if (environment === "mixed") return ["rain", "heat", "wind"];
  return ["rain", "heat", "cold", "wind", "uv"];
}

function poi(seed: PoiSeed): CuratedPoi {
  return {
    ...seed,
    weatherSensitivity: seed.weatherSensitivity ?? sensitivity(seed.environment),
    provenance: "curated-v1",
  };
}

const CURATED_POIS: ReadonlyArray<CuratedPoi> = [
  // Tokyo
  poi({
    id: "jp-tokyo-sensoji",
    cityId: "jp-tokyo",
    name: { en: "Senso-ji", "zh-cn": "浅草寺", "zh-hant": "淺草寺" },
    latitude: 35.7148,
    longitude: 139.7967,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-tokyo-national-museum",
    cityId: "jp-tokyo",
    name: { en: "Tokyo National Museum", "zh-cn": "东京国立博物馆", "zh-hant": "東京國立博物館" },
    latitude: 35.7188,
    longitude: 139.7765,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-tokyo-ueno-park",
    cityId: "jp-tokyo",
    name: { en: "Ueno Park", "zh-cn": "上野公园", "zh-hant": "上野公園" },
    latitude: 35.7141,
    longitude: 139.7741,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-tokyo-meiji-shrine",
    cityId: "jp-tokyo",
    name: { en: "Meiji Shrine", "zh-cn": "明治神宫", "zh-hant": "明治神宮" },
    latitude: 35.6764,
    longitude: 139.6993,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-tokyo-shibuya-sky",
    cityId: "jp-tokyo",
    name: { en: "Shibuya Sky", "zh-cn": "涩谷 Sky", "zh-hant": "澀谷 Sky" },
    latitude: 35.6584,
    longitude: 139.7022,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 90,
    reservation: "recommended",
    recommendedWindow: "evening",
  }),
  poi({
    id: "jp-tokyo-teamlab-planets",
    cityId: "jp-tokyo",
    name: { en: "teamLab Planets", "zh-cn": "teamLab Planets", "zh-hant": "teamLab Planets" },
    latitude: 35.6491,
    longitude: 139.7898,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "required",
    recommendedWindow: "any",
  }),
  poi({
    id: "jp-tokyo-skytree",
    cityId: "jp-tokyo",
    name: { en: "Tokyo Skytree", "zh-cn": "东京晴空塔", "zh-hant": "東京晴空塔" },
    latitude: 35.7101,
    longitude: 139.8107,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "recommended",
    recommendedWindow: "evening",
  }),
  poi({
    id: "jp-tokyo-sumida-aquarium",
    cityId: "jp-tokyo",
    name: { en: "Sumida Aquarium", "zh-cn": "墨田水族馆", "zh-hant": "墨田水族館" },
    latitude: 35.71,
    longitude: 139.8102,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-tokyo-nature-science-museum",
    cityId: "jp-tokyo",
    name: {
      en: "National Museum of Nature and Science",
      "zh-cn": "国立科学博物馆",
      "zh-hant": "國立科學博物館",
    },
    latitude: 35.7163,
    longitude: 139.7764,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-tokyo-tsukiji",
    cityId: "jp-tokyo",
    name: { en: "Tsukiji Outer Market", "zh-cn": "筑地场外市场", "zh-hant": "築地場外市場" },
    latitude: 35.6655,
    longitude: 139.7707,
    category: "food",
    environment: "mixed",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-tokyo-imperial-east-gardens",
    cityId: "jp-tokyo",
    name: { en: "Imperial Palace East Gardens", "zh-cn": "皇居东御苑", "zh-hant": "皇居東御苑" },
    latitude: 35.6852,
    longitude: 139.7568,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-tokyo-odaiba",
    cityId: "jp-tokyo",
    name: { en: "Odaiba", "zh-cn": "台场", "zh-hant": "台場" },
    latitude: 35.6278,
    longitude: 139.7765,
    category: "leisure",
    environment: "mixed",
    typicalDurationMinutes: 180,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-tokyo-mori-art",
    cityId: "jp-tokyo",
    name: { en: "Mori Art Museum", "zh-cn": "森美术馆", "zh-hant": "森美術館" },
    latitude: 35.6605,
    longitude: 139.7292,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-tokyo-hamarikyu",
    cityId: "jp-tokyo",
    name: { en: "Hamarikyu Gardens", "zh-cn": "浜离宫恩赐庭园", "zh-hant": "濱離宮恩賜庭園" },
    latitude: 35.6596,
    longitude: 139.7634,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-tokyo-ginza",
    cityId: "jp-tokyo",
    name: { en: "Ginza", "zh-cn": "银座", "zh-hant": "銀座" },
    latitude: 35.6717,
    longitude: 139.765,
    category: "shopping",
    environment: "mixed",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),

  // Kyoto
  poi({
    id: "jp-kyoto-fushimi-inari",
    cityId: "jp-kyoto",
    name: { en: "Fushimi Inari Taisha", "zh-cn": "伏见稻荷大社", "zh-hant": "伏見稻荷大社" },
    latitude: 34.9671,
    longitude: 135.7727,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-kyoto-kiyomizu",
    cityId: "jp-kyoto",
    name: { en: "Kiyomizu-dera", "zh-cn": "清水寺", "zh-hant": "清水寺" },
    latitude: 34.9949,
    longitude: 135.785,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-kyoto-arashiyama",
    cityId: "jp-kyoto",
    name: { en: "Arashiyama Bamboo Grove", "zh-cn": "岚山竹林", "zh-hant": "嵐山竹林" },
    latitude: 35.017,
    longitude: 135.6713,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-kyoto-tenryuji",
    cityId: "jp-kyoto",
    name: { en: "Tenryu-ji", "zh-cn": "天龙寺", "zh-hant": "天龍寺" },
    latitude: 35.0158,
    longitude: 135.6738,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-kyoto-nishiki",
    cityId: "jp-kyoto",
    name: { en: "Nishiki Market", "zh-cn": "锦市场", "zh-hant": "錦市場" },
    latitude: 35.005,
    longitude: 135.7648,
    category: "food",
    environment: "mixed",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-kyoto-railway-museum",
    cityId: "jp-kyoto",
    name: { en: "Kyoto Railway Museum", "zh-cn": "京都铁道博物馆", "zh-hant": "京都鐵道博物館" },
    latitude: 34.9875,
    longitude: 135.7415,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 180,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-kyoto-aquarium",
    cityId: "jp-kyoto",
    name: { en: "Kyoto Aquarium", "zh-cn": "京都水族馆", "zh-hant": "京都水族館" },
    latitude: 34.9872,
    longitude: 135.747,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-kyoto-nijo",
    cityId: "jp-kyoto",
    name: { en: "Nijo Castle", "zh-cn": "二条城", "zh-hant": "二條城" },
    latitude: 35.0142,
    longitude: 135.7482,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-kyoto-kinkakuji",
    cityId: "jp-kyoto",
    name: { en: "Kinkaku-ji", "zh-cn": "金阁寺", "zh-hant": "金閣寺" },
    latitude: 35.0394,
    longitude: 135.7292,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-kyoto-gion",
    cityId: "jp-kyoto",
    name: { en: "Gion", "zh-cn": "祇园", "zh-hant": "祇園" },
    latitude: 35.0037,
    longitude: 135.7788,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "evening",
  }),
  poi({
    id: "jp-kyoto-national-museum",
    cityId: "jp-kyoto",
    name: { en: "Kyoto National Museum", "zh-cn": "京都国立博物馆", "zh-hant": "京都國立博物館" },
    latitude: 34.99,
    longitude: 135.773,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-kyoto-sanjusangendo",
    cityId: "jp-kyoto",
    name: { en: "Sanjusangen-do", "zh-cn": "三十三间堂", "zh-hant": "三十三間堂" },
    latitude: 34.9879,
    longitude: 135.7717,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 75,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-kyoto-philosophers-path",
    cityId: "jp-kyoto",
    name: { en: "Philosopher's Path", "zh-cn": "哲学之道", "zh-hant": "哲學之道" },
    latitude: 35.0267,
    longitude: 135.7954,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-kyoto-kyoto-station",
    cityId: "jp-kyoto",
    name: { en: "Kyoto Station Building", "zh-cn": "京都站大楼", "zh-hant": "京都站大樓" },
    latitude: 34.9858,
    longitude: 135.7588,
    category: "shopping",
    environment: "indoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "evening",
  }),
  poi({
    id: "jp-kyoto-toei",
    cityId: "jp-kyoto",
    name: { en: "Toei Kyoto Studio Park", "zh-cn": "东映太秦映画村", "zh-hant": "東映太秦映畫村" },
    latitude: 35.0162,
    longitude: 135.7084,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 240,
    reservation: "recommended",
    recommendedWindow: "any",
  }),

  // Osaka
  poi({
    id: "jp-osaka-castle",
    cityId: "jp-osaka",
    name: { en: "Osaka Castle", "zh-cn": "大阪城", "zh-hant": "大阪城" },
    latitude: 34.6873,
    longitude: 135.5262,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-osaka-kaiyukan",
    cityId: "jp-osaka",
    name: { en: "Osaka Aquarium Kaiyukan", "zh-cn": "大阪海游馆", "zh-hant": "大阪海遊館" },
    latitude: 34.6545,
    longitude: 135.4289,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 180,
    reservation: "recommended",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-osaka-usj",
    cityId: "jp-osaka",
    name: { en: "Universal Studios Japan", "zh-cn": "日本环球影城", "zh-hant": "日本環球影城" },
    latitude: 34.6654,
    longitude: 135.4323,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 600,
    reservation: "required",
    recommendedWindow: "any",
  }),
  poi({
    id: "jp-osaka-dotonbori",
    cityId: "jp-osaka",
    name: { en: "Dotonbori", "zh-cn": "道顿堀", "zh-hant": "道頓堀" },
    latitude: 34.6687,
    longitude: 135.5013,
    category: "food",
    environment: "mixed",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "evening",
  }),
  poi({
    id: "jp-osaka-umeda-sky",
    cityId: "jp-osaka",
    name: { en: "Umeda Sky Building", "zh-cn": "梅田蓝天大厦", "zh-hant": "梅田藍天大廈" },
    latitude: 34.7053,
    longitude: 135.49,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 90,
    reservation: "recommended",
    recommendedWindow: "evening",
  }),
  poi({
    id: "jp-osaka-kuromon",
    cityId: "jp-osaka",
    name: { en: "Kuromon Ichiba Market", "zh-cn": "黑门市场", "zh-hant": "黑門市場" },
    latitude: 34.6652,
    longitude: 135.5065,
    category: "food",
    environment: "mixed",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-osaka-history-museum",
    cityId: "jp-osaka",
    name: { en: "Osaka Museum of History", "zh-cn": "大阪历史博物馆", "zh-hant": "大阪歷史博物館" },
    latitude: 34.6826,
    longitude: 135.5207,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-osaka-nakanoshima-art",
    cityId: "jp-osaka",
    name: {
      en: "Nakanoshima Museum of Art",
      "zh-cn": "大阪中之岛美术馆",
      "zh-hant": "大阪中之島美術館",
    },
    latitude: 34.691,
    longitude: 135.4887,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-osaka-abenoharukas",
    cityId: "jp-osaka",
    name: { en: "Abeno Harukas", "zh-cn": "阿倍野 Harukas", "zh-hant": "阿倍野 Harukas" },
    latitude: 34.6459,
    longitude: 135.5134,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "recommended",
    recommendedWindow: "evening",
  }),
  poi({
    id: "jp-osaka-shitennoji",
    cityId: "jp-osaka",
    name: { en: "Shitenno-ji", "zh-cn": "四天王寺", "zh-hant": "四天王寺" },
    latitude: 34.6544,
    longitude: 135.5165,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-osaka-sumiyoshi",
    cityId: "jp-osaka",
    name: { en: "Sumiyoshi Taisha", "zh-cn": "住吉大社", "zh-hant": "住吉大社" },
    latitude: 34.6127,
    longitude: 135.4929,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-osaka-tennoji-zoo",
    cityId: "jp-osaka",
    name: { en: "Tennoji Zoo", "zh-cn": "天王寺动物园", "zh-hant": "天王寺動物園" },
    latitude: 34.6514,
    longitude: 135.5084,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 180,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "jp-osaka-shinsaibashi",
    cityId: "jp-osaka",
    name: { en: "Shinsaibashi", "zh-cn": "心斋桥", "zh-hant": "心齋橋" },
    latitude: 34.6749,
    longitude: 135.5005,
    category: "shopping",
    environment: "mixed",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-osaka-national-art",
    cityId: "jp-osaka",
    name: {
      en: "National Museum of Art, Osaka",
      "zh-cn": "国立国际美术馆",
      "zh-hant": "國立國際美術館",
    },
    latitude: 34.6919,
    longitude: 135.4922,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "jp-osaka-tempozan",
    cityId: "jp-osaka",
    name: { en: "Tempozan Harbor Village", "zh-cn": "天保山港湾村", "zh-hant": "天保山港灣村" },
    latitude: 34.6549,
    longitude: 135.43,
    category: "leisure",
    environment: "mixed",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),

  // Seoul
  poi({
    id: "kr-seoul-gyeongbokgung",
    cityId: "kr-seoul",
    name: { en: "Gyeongbokgung Palace", "zh-cn": "景福宫", "zh-hant": "景福宮" },
    latitude: 37.5796,
    longitude: 126.977,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "kr-seoul-bukchon",
    cityId: "kr-seoul",
    name: { en: "Bukchon Hanok Village", "zh-cn": "北村韩屋村", "zh-hant": "北村韓屋村" },
    latitude: 37.5826,
    longitude: 126.983,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "kr-seoul-n-tower",
    cityId: "kr-seoul",
    name: { en: "N Seoul Tower", "zh-cn": "N首尔塔", "zh-hant": "N首爾塔" },
    latitude: 37.5512,
    longitude: 126.9882,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 120,
    reservation: "recommended",
    recommendedWindow: "evening",
  }),
  poi({
    id: "kr-seoul-national-museum",
    cityId: "kr-seoul",
    name: {
      en: "National Museum of Korea",
      "zh-cn": "韩国国立中央博物馆",
      "zh-hant": "韓國國立中央博物館",
    },
    latitude: 37.5239,
    longitude: 126.9802,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 180,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "kr-seoul-coex-aquarium",
    cityId: "kr-seoul",
    name: { en: "COEX Aquarium", "zh-cn": "COEX水族馆", "zh-hant": "COEX水族館" },
    latitude: 37.5111,
    longitude: 127.059,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "kr-seoul-lotte-world",
    cityId: "kr-seoul",
    name: { en: "Lotte World", "zh-cn": "乐天世界", "zh-hant": "樂天世界" },
    latitude: 37.5111,
    longitude: 127.0982,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 360,
    reservation: "recommended",
    recommendedWindow: "any",
  }),
  poi({
    id: "kr-seoul-seoul-forest",
    cityId: "kr-seoul",
    name: { en: "Seoul Forest", "zh-cn": "首尔林", "zh-hant": "首爾林" },
    latitude: 37.5444,
    longitude: 127.0374,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "kr-seoul-myeongdong",
    cityId: "kr-seoul",
    name: { en: "Myeongdong", "zh-cn": "明洞", "zh-hant": "明洞" },
    latitude: 37.5636,
    longitude: 126.9869,
    category: "shopping",
    environment: "mixed",
    typicalDurationMinutes: 180,
    reservation: "none",
    recommendedWindow: "evening",
  }),
  poi({
    id: "kr-seoul-gwangjang",
    cityId: "kr-seoul",
    name: { en: "Gwangjang Market", "zh-cn": "广藏市场", "zh-hant": "廣藏市場" },
    latitude: 37.57,
    longitude: 126.9996,
    category: "food",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "kr-seoul-war-memorial",
    cityId: "kr-seoul",
    name: { en: "War Memorial of Korea", "zh-cn": "韩国战争纪念馆", "zh-hant": "韓國戰爭紀念館" },
    latitude: 37.5366,
    longitude: 126.977,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "kr-seoul-leeum",
    cityId: "kr-seoul",
    name: { en: "Leeum Museum of Art", "zh-cn": "Leeum三星美术馆", "zh-hant": "Leeum三星美術館" },
    latitude: 37.5384,
    longitude: 126.9991,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "recommended",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "kr-seoul-ddp",
    cityId: "kr-seoul",
    name: { en: "Dongdaemun Design Plaza", "zh-cn": "东大门设计广场", "zh-hant": "東大門設計廣場" },
    latitude: 37.5665,
    longitude: 127.0092,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "evening",
  }),
  poi({
    id: "kr-seoul-cheonggyecheon",
    cityId: "kr-seoul",
    name: { en: "Cheonggyecheon Stream", "zh-cn": "清溪川", "zh-hant": "清溪川" },
    latitude: 37.569,
    longitude: 126.9784,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "evening",
  }),
  poi({
    id: "kr-seoul-han-river",
    cityId: "kr-seoul",
    name: { en: "Yeouido Hangang Park", "zh-cn": "汝矣岛汉江公园", "zh-hant": "汝矣島漢江公園" },
    latitude: 37.5284,
    longitude: 126.9327,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "evening",
  }),
  poi({
    id: "kr-seoul-starfield-library",
    cityId: "kr-seoul",
    name: { en: "Starfield Library", "zh-cn": "星空图书馆", "zh-hant": "星空圖書館" },
    latitude: 37.5102,
    longitude: 127.0601,
    category: "leisure",
    environment: "indoor",
    typicalDurationMinutes: 75,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),

  // Jeju
  poi({
    id: "kr-jeju-seongsan",
    cityId: "kr-jeju",
    name: { en: "Seongsan Ilchulbong", "zh-cn": "城山日出峰", "zh-hant": "城山日出峰" },
    latitude: 33.4581,
    longitude: 126.9425,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "kr-jeju-hallasan",
    cityId: "kr-jeju",
    name: { en: "Hallasan National Park", "zh-cn": "汉拿山国立公园", "zh-hant": "漢拏山國立公園" },
    latitude: 33.3617,
    longitude: 126.5292,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 360,
    reservation: "recommended",
    recommendedWindow: "morning",
  }),
  poi({
    id: "kr-jeju-cheonjiyeon",
    cityId: "kr-jeju",
    name: { en: "Cheonjiyeon Waterfall", "zh-cn": "天地渊瀑布", "zh-hant": "天地淵瀑布" },
    latitude: 33.2469,
    longitude: 126.5544,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "kr-jeju-jusangjeolli",
    cityId: "kr-jeju",
    name: { en: "Jusangjeolli Cliff", "zh-cn": "柱状节理带", "zh-hant": "柱狀節理帶" },
    latitude: 33.2379,
    longitude: 126.4265,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 75,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "kr-jeju-osulloc",
    cityId: "kr-jeju",
    name: { en: "O'Sulloc Tea Museum", "zh-cn": "雪绿茶博物馆", "zh-hant": "雪綠茶博物館" },
    latitude: 33.3059,
    longitude: 126.2895,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "kr-jeju-aqua-planet",
    cityId: "kr-jeju",
    name: { en: "Aqua Planet Jeju", "zh-cn": "济州 Aqua Planet", "zh-hant": "濟州 Aqua Planet" },
    latitude: 33.433,
    longitude: 126.9278,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 180,
    reservation: "recommended",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "kr-jeju-arte-museum",
    cityId: "kr-jeju",
    name: { en: "Arte Museum Jeju", "zh-cn": "Arte Museum 济州", "zh-hant": "Arte Museum 濟州" },
    latitude: 33.396,
    longitude: 126.3457,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "recommended",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "kr-jeju-camellia-hill",
    cityId: "kr-jeju",
    name: { en: "Camellia Hill", "zh-cn": "山茶花之丘", "zh-hant": "山茶花之丘" },
    latitude: 33.2897,
    longitude: 126.37,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "kr-jeju-yongduam",
    cityId: "kr-jeju",
    name: { en: "Yongduam Rock", "zh-cn": "龙头岩", "zh-hant": "龍頭岩" },
    latitude: 33.5157,
    longitude: 126.5118,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 60,
    reservation: "none",
    recommendedWindow: "evening",
  }),
  poi({
    id: "kr-jeju-dongmun",
    cityId: "kr-jeju",
    name: { en: "Dongmun Traditional Market", "zh-cn": "东门传统市场", "zh-hant": "東門傳統市場" },
    latitude: 33.5116,
    longitude: 126.526,
    category: "food",
    environment: "mixed",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "evening",
  }),
  poi({
    id: "kr-jeju-spirited-garden",
    cityId: "kr-jeju",
    name: { en: "Spirited Garden", "zh-cn": "思索之苑", "zh-hant": "思索之苑" },
    latitude: 33.3249,
    longitude: 126.2557,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "kr-jeju-folk-village",
    cityId: "kr-jeju",
    name: { en: "Jeju Folk Village", "zh-cn": "济州民俗村", "zh-hant": "濟州民俗村" },
    latitude: 33.3224,
    longitude: 126.8414,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "kr-jeju-bijarim",
    cityId: "kr-jeju",
    name: { en: "Bijarim Forest", "zh-cn": "榧子林", "zh-hant": "榧子林" },
    latitude: 33.4913,
    longitude: 126.8114,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "kr-jeju-jeju-national-museum",
    cityId: "kr-jeju",
    name: { en: "Jeju National Museum", "zh-cn": "济州国立博物馆", "zh-hant": "濟州國立博物館" },
    latitude: 33.5138,
    longitude: 126.5487,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "kr-jeju-seopjikoji",
    cityId: "kr-jeju",
    name: { en: "Seopjikoji", "zh-cn": "涉地可支", "zh-hant": "涉地可支" },
    latitude: 33.4239,
    longitude: 126.9294,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),

  // Bangkok
  poi({
    id: "th-bangkok-grand-palace",
    cityId: "th-bangkok",
    name: { en: "Grand Palace", "zh-cn": "曼谷大皇宫", "zh-hant": "曼谷大皇宮" },
    latitude: 13.75,
    longitude: 100.4913,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "th-bangkok-wat-arun",
    cityId: "th-bangkok",
    name: { en: "Wat Arun", "zh-cn": "郑王庙", "zh-hant": "鄭王廟" },
    latitude: 13.7437,
    longitude: 100.4889,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "th-bangkok-wat-pho",
    cityId: "th-bangkok",
    name: { en: "Wat Pho", "zh-cn": "卧佛寺", "zh-hant": "臥佛寺" },
    latitude: 13.7466,
    longitude: 100.493,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "th-bangkok-iconsiam",
    cityId: "th-bangkok",
    name: { en: "ICONSIAM", "zh-cn": "ICONSIAM", "zh-hant": "ICONSIAM" },
    latitude: 13.7266,
    longitude: 100.51,
    category: "shopping",
    environment: "indoor",
    typicalDurationMinutes: 180,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "th-bangkok-jim-thompson",
    cityId: "th-bangkok",
    name: { en: "Jim Thompson House", "zh-cn": "吉姆汤普森之家", "zh-hant": "吉姆湯普森之家" },
    latitude: 13.7492,
    longitude: 100.5283,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "th-bangkok-national-museum",
    cityId: "th-bangkok",
    name: { en: "Bangkok National Museum", "zh-cn": "曼谷国立博物馆", "zh-hant": "曼谷國立博物館" },
    latitude: 13.7578,
    longitude: 100.4924,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "th-bangkok-sea-life",
    cityId: "th-bangkok",
    name: {
      en: "SEA LIFE Bangkok Ocean World",
      "zh-cn": "曼谷暹罗海洋世界",
      "zh-hant": "曼谷暹羅海洋世界",
    },
    latitude: 13.7462,
    longitude: 100.535,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 150,
    reservation: "recommended",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "th-bangkok-museum-siam",
    cityId: "th-bangkok",
    name: { en: "Museum Siam", "zh-cn": "暹罗博物馆", "zh-hant": "暹羅博物館" },
    latitude: 13.7443,
    longitude: 100.4945,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "th-bangkok-chatuchak",
    cityId: "th-bangkok",
    name: { en: "Chatuchak Market", "zh-cn": "乍都乍周末市场", "zh-hant": "乍都乍週末市場" },
    latitude: 13.7999,
    longitude: 100.5501,
    category: "shopping",
    environment: "mixed",
    typicalDurationMinutes: 180,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "th-bangkok-yaowarat",
    cityId: "th-bangkok",
    name: { en: "Yaowarat Road", "zh-cn": "耀华力路唐人街", "zh-hant": "耀華力路唐人街" },
    latitude: 13.74,
    longitude: 100.51,
    category: "food",
    environment: "outdoor",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "evening",
  }),
  poi({
    id: "th-bangkok-lumpini",
    cityId: "th-bangkok",
    name: { en: "Lumphini Park", "zh-cn": "伦披尼公园", "zh-hant": "倫披尼公園" },
    latitude: 13.7305,
    longitude: 100.5418,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "th-bangkok-mahanakhon",
    cityId: "th-bangkok",
    name: {
      en: "Mahanakhon SkyWalk",
      "zh-cn": "王权云顶大厦 SkyWalk",
      "zh-hant": "王權雲頂大廈 SkyWalk",
    },
    latitude: 13.7235,
    longitude: 100.5283,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 90,
    reservation: "recommended",
    recommendedWindow: "evening",
  }),
  poi({
    id: "th-bangkok-bacc",
    cityId: "th-bangkok",
    name: {
      en: "Bangkok Art and Culture Centre",
      "zh-cn": "曼谷艺术文化中心",
      "zh-hant": "曼谷藝術文化中心",
    },
    latitude: 13.7468,
    longitude: 100.53,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "th-bangkok-terminal21",
    cityId: "th-bangkok",
    name: {
      en: "Terminal 21 Asok",
      "zh-cn": "Terminal 21 航站楼商场",
      "zh-hant": "Terminal 21 航站樓商場",
    },
    latitude: 13.7379,
    longitude: 100.5601,
    category: "shopping",
    environment: "indoor",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "th-bangkok-benjakitti",
    cityId: "th-bangkok",
    name: { en: "Benjakitti Park", "zh-cn": "班嘉奇蒂公园", "zh-hant": "班嘉奇蒂公園" },
    latitude: 13.7296,
    longitude: 100.5581,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "evening",
  }),

  // Phuket
  poi({
    id: "th-phuket-old-town",
    cityId: "th-phuket",
    name: { en: "Phuket Old Town", "zh-cn": "普吉老城", "zh-hant": "普吉老城" },
    latitude: 7.884,
    longitude: 98.3874,
    category: "leisure",
    environment: "mixed",
    typicalDurationMinutes: 180,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "th-phuket-kata",
    cityId: "th-phuket",
    name: { en: "Kata Beach", "zh-cn": "卡塔海滩", "zh-hant": "卡塔海灘" },
    latitude: 7.8212,
    longitude: 98.2983,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 180,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "th-phuket-karon",
    cityId: "th-phuket",
    name: { en: "Karon Beach", "zh-cn": "卡伦海滩", "zh-hant": "卡倫海灘" },
    latitude: 7.8437,
    longitude: 98.2931,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 180,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "th-phuket-promthep",
    cityId: "th-phuket",
    name: { en: "Promthep Cape", "zh-cn": "神仙半岛", "zh-hant": "神仙半島" },
    latitude: 7.7594,
    longitude: 98.303,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "evening",
  }),
  poi({
    id: "th-phuket-aquarium",
    cityId: "th-phuket",
    name: { en: "Phuket Aquarium", "zh-cn": "普吉水族馆", "zh-hant": "普吉水族館" },
    latitude: 7.8021,
    longitude: 98.4078,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "th-phuket-thai-hua",
    cityId: "th-phuket",
    name: { en: "Thai Hua Museum", "zh-cn": "泰华博物馆", "zh-hant": "泰華博物館" },
    latitude: 7.8857,
    longitude: 98.3862,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "th-phuket-wat-chalong",
    cityId: "th-phuket",
    name: { en: "Wat Chalong", "zh-cn": "查龙寺", "zh-hant": "查龍寺" },
    latitude: 7.8467,
    longitude: 98.3368,
    category: "attraction",
    environment: "mixed",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "th-phuket-nai-harn",
    cityId: "th-phuket",
    name: { en: "Nai Harn Beach", "zh-cn": "奈涵海滩", "zh-hant": "奈涵海灘" },
    latitude: 7.7757,
    longitude: 98.3067,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 180,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "th-phuket-central",
    cityId: "th-phuket",
    name: {
      en: "Central Phuket",
      "zh-cn": "Central Phuket 商场",
      "zh-hant": "Central Phuket 商場",
    },
    latitude: 7.8912,
    longitude: 98.3671,
    category: "shopping",
    environment: "indoor",
    typicalDurationMinutes: 180,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "th-phuket-chinpracha",
    cityId: "th-phuket",
    name: { en: "Chinpracha House", "zh-cn": "钦普拉差老宅", "zh-hant": "欽普拉差老宅" },
    latitude: 7.887,
    longitude: 98.3844,
    category: "attraction",
    environment: "indoor",
    typicalDurationMinutes: 75,
    reservation: "none",
    recommendedWindow: "afternoon",
  }),
  poi({
    id: "th-phuket-rang-hill",
    cityId: "th-phuket",
    name: { en: "Khao Rang Hill", "zh-cn": "考朗山观景台", "zh-hant": "考朗山觀景台" },
    latitude: 7.8935,
    longitude: 98.3801,
    category: "attraction",
    environment: "outdoor",
    typicalDurationMinutes: 75,
    reservation: "none",
    recommendedWindow: "evening",
  }),
  poi({
    id: "th-phuket-chillva",
    cityId: "th-phuket",
    name: { en: "Chillva Market", "zh-cn": "Chillva 夜市", "zh-hant": "Chillva 夜市" },
    latitude: 7.9094,
    longitude: 98.3812,
    category: "food",
    environment: "mixed",
    typicalDurationMinutes: 120,
    reservation: "none",
    recommendedWindow: "evening",
  }),
  poi({
    id: "th-phuket-mai-khao",
    cityId: "th-phuket",
    name: { en: "Mai Khao Beach", "zh-cn": "迈考海滩", "zh-hant": "邁考海灘" },
    latitude: 8.1262,
    longitude: 98.2988,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 150,
    reservation: "none",
    recommendedWindow: "morning",
  }),
  poi({
    id: "th-phuket-andamanda",
    cityId: "th-phuket",
    name: {
      en: "Andamanda Phuket",
      "zh-cn": "Andamanda 普吉水上乐园",
      "zh-hant": "Andamanda 普吉水上樂園",
    },
    latitude: 7.899,
    longitude: 98.3667,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 300,
    reservation: "recommended",
    recommendedWindow: "any",
  }),
  poi({
    id: "th-phuket-saphan-hin",
    cityId: "th-phuket",
    name: { en: "Saphan Hin Park", "zh-cn": "沙潘欣公园", "zh-hant": "沙潘欣公園" },
    latitude: 7.8724,
    longitude: 98.403,
    category: "leisure",
    environment: "outdoor",
    typicalDurationMinutes: 90,
    reservation: "none",
    recommendedWindow: "evening",
  }),
];

const curatedNames = new Set(
  CURATED_POIS.map((item) => `${item.cityId}|${item.name.en.trim().toLocaleLowerCase("en-US")}`),
);
const POIS: ReadonlyArray<CuratedPoi> = [
  ...CURATED_POIS,
  ...OSM_PILOT_POIS.filter(
    (item) => !curatedNames.has(`${item.cityId}|${item.name.en.trim().toLocaleLowerCase("en-US")}`),
  ),
];

export const POI_DATA_ATTRIBUTIONS = Object.freeze([
  "Curated travel metadata: Where Not Rain curated-v1",
  "OpenStreetMap-derived candidates: © OpenStreetMap contributors, ODbL 1.0",
]);

const BY_CITY = new Map<string, ReadonlyArray<CuratedPoi>>();
for (const item of POIS) {
  const current = BY_CITY.get(item.cityId) ?? [];
  BY_CITY.set(item.cityId, [...current, item]);
}

export const PILOT_POI_CITY_IDS = Object.freeze([
  "jp-tokyo",
  "jp-kyoto",
  "jp-osaka",
  "kr-seoul",
  "kr-jeju",
  "th-bangkok",
  "th-phuket",
] as const);

export function listCuratedPois(cityId: string): ReadonlyArray<CuratedPoi> {
  return BY_CITY.get(cityId) ?? [];
}

export function findCuratedPoi(poiId: string): CuratedPoi | null {
  return POIS.find((item) => item.id === poiId) ?? null;
}

export function poiName(poi: CuratedPoi, locale: PoiLocale): string {
  return poi.name[locale];
}

export function findWeatherFallbacks(
  cityId: string,
  excludedPoiId: string | null,
  limit = 3,
): ReadonlyArray<CuratedPoi> {
  return listCuratedPois(cityId)
    .filter((item) => item.id !== excludedPoiId && item.environment === "indoor")
    .sort((left, right) => {
      const reservationWeight = (value: TripActivityReservation): number =>
        value === "none" ? 0 : value === "recommended" ? 1 : 2;
      const diff = reservationWeight(left.reservation) - reservationWeight(right.reservation);
      if (diff !== 0) return diff;
      return left.typicalDurationMinutes - right.typicalDurationMinutes;
    })
    .slice(0, Math.max(0, Math.min(limit, 5)));
}
