import type {
  TripCityOption,
  TripForecastDay,
  TripWorkspace,
  TripWorkspaceTemplateSummary,
  WorkspaceDayDecision,
} from "./workspace";

const PHRASES: ReadonlyArray<readonly [string, string]> = [
  ["印度尼西亚", "印尼"],
  ["马来西亚", "馬來西亞"],
  ["菲律宾", "菲律賓"],
  ["韩国", "南韓"],
  ["泰国", "泰國"],
  ["东京", "東京"],
  ["首尔", "首爾"],
  ["济州", "濟州"],
  ["普吉岛", "普吉島"],
  ["清迈", "清邁"],
  ["河内", "河內"],
  ["岘港", "峴港"],
  ["会安", "會安"],
  ["槟城", "檳城"],
  ["兰卡威", "蘭卡威"],
  ["马六甲", "馬六甲"],
  ["巴厘岛", "峇里島"],
  ["雅加达", "雅加達"],
  ["马尼拉", "馬尼拉"],
  ["宿务", "宿霧"],
  ["长滩岛", "長灘島"],
  ["金边", "金邊"],
  ["福冈", "福岡"],
  ["天气待确认", "天氣待確認"],
  ["天气变化", "天氣變化"],
  ["多云", "多雲"],
  ["阵雨", "陣雨"],
  ["阵雪", "陣雪"],
  ["我的天气旅行", "我的天氣行程"],
  ["亲子", "親子"],
  ["环球影城", "環球影城"],
  ["涩谷", "澀谷"],
  ["岚山", "嵐山"],
  ["天龙寺", "天龍寺"],
  ["铁道博物馆", "鐵道博物館"],
  ["郑王庙", "鄭王廟"],
  ["神仙半岛", "神仙半島"],
  ["皮皮岛", "皮皮島"],
  ["首尔林", "首爾林"],
  ["汉江", "漢江"],
  ["国立中央博物馆", "國立中央博物館"],
  ["海云台", "海雲臺"],
  ["广安里", "廣安里"],
];

const CHARACTERS = new Map<string, string>([
  ["气", "氣"],
  ["这", "這"],
  ["获", "獲"],
  ["选", "選"],
  ["择", "擇"],
  ["点", "點"],
  ["击", "擊"],
  ["后", "後"],
  ["内", "內"],
  ["馆", "館"],
  ["场", "場"],
  ["备", "備"],
  ["轻", "輕"],
  ["带", "帶"],
  ["动", "動"],
  ["风", "風"],
  ["强", "強"],
  ["边", "邊"],
  ["复", "複"],
  ["开", "開"],
  ["状", "狀"],
  ["态", "態"],
  ["显", "顯"],
  ["凉", "涼"],
  ["较", "較"],
  ["缩", "縮"],
  ["预", "預"],
  ["览", "覽"],
  ["计", "計"],
  ["议", "議"],
  ["关", "關"],
  ["间", "間"],
  ["门", "門"],
  ["车", "車"],
  ["线", "線"],
  ["乐", "樂"],
  ["处", "處"],
  ["见", "見"],
  ["阵", "陣"],
  ["观", "觀"],
  ["云", "雲"],
  ["雾", "霧"],
  ["变", "變"],
  ["认", "認"],
  ["现", "現"],
  ["携", "攜"],
  ["进", "進"],
  ["稳", "穩"],
  ["应", "應"],
  ["续", "續"],
  ["决", "決"],
  ["过", "過"],
  ["页", "頁"],
  ["码", "碼"],
  ["载", "載"],
  ["录", "錄"],
  ["标", "標"],
  ["题", "題"],
  ["识", "識"],
  ["节", "節"],
  ["个", "個"],
  ["导", "導"],
  ["设", "設"],
  ["离", "離"],
  ["链", "鏈"],
  ["户", "戶"],
  ["实", "實"],
  ["优", "優"],
  ["发", "發"],
  ["体", "體"],
  ["验", "驗"],
  ["与", "與"],
  ["为", "為"],
  ["将", "將"],
  ["从", "從"],
  ["对", "對"],
  ["无", "無"],
  ["说", "說"],
  ["写", "寫"],
  ["读", "讀"],
  ["让", "讓"],
  ["够", "夠"],
  ["长", "長"],
  ["张", "張"],
  ["结", "結"],
  ["构", "構"],
  ["数", "數"],
  ["据", "據"],
  ["该", "該"],
  ["仅", "僅"],
  ["时", "時"],
  ["总", "總"],
  ["险", "險"],
  ["级", "級"],
  ["适", "適"],
  ["当", "當"],
  ["组", "組"],
  ["织", "織"],
  ["画", "畫"],
  ["师", "師"],
  ["万", "萬"],
  ["华", "華"],
  ["价", "價"],
  ["类", "類"],
  ["术", "術"],
  ["转", "轉"],
  ["换", "換"],
  ["调", "調"],
  ["阳", "陽"],
  ["阴", "陰"],
  ["湿", "濕"],
  ["热", "熱"],
  ["暂", "暫"],
  ["还", "還"],
  ["请", "請"],
  ["添", "添"],
  ["补", "補"],
  ["费", "費"],
  ["执", "執"],
  ["额", "額"],
  ["压", "壓"],
  ["测", "測"],
]);

export function toTraditionalText(value: string): string {
  let result = value;
  for (const [source, target] of PHRASES) result = result.replaceAll(source, target);
  return [...result].map((character) => CHARACTERS.get(character) ?? character).join("");
}

export function toTraditionalWorkspace(workspace: TripWorkspace): TripWorkspace {
  return {
    ...workspace,
    title: toTraditionalText(workspace.title),
    days: workspace.days.map((day) => ({
      ...day,
      cityName: toTraditionalText(day.cityName),
      countryName: toTraditionalText(day.countryName),
      activities: day.activities.map(toTraditionalText),
      notes: toTraditionalText(day.notes),
    })),
  };
}

export function toTraditionalCity(city: TripCityOption): TripCityOption {
  return {
    ...city,
    cityName: toTraditionalText(city.cityName),
    countryName: toTraditionalText(city.countryName),
  };
}

export function toTraditionalForecast(forecast: TripForecastDay): TripForecastDay {
  return { ...forecast, condition: toTraditionalText(forecast.condition) };
}

export function toTraditionalDecision(decision: WorkspaceDayDecision): WorkspaceDayDecision {
  return {
    ...decision,
    summary: toTraditionalText(decision.summary),
    reasons: decision.reasons.map(toTraditionalText),
    planB: toTraditionalText(decision.planB),
  };
}

export function toTraditionalTemplate(
  template: TripWorkspaceTemplateSummary,
): TripWorkspaceTemplateSummary {
  return {
    ...template,
    title: toTraditionalText(template.title),
    description: toTraditionalText(template.description),
    duration: toTraditionalText(template.duration),
    route: toTraditionalText(template.route),
  };
}
