import type { TripDay } from "../types";
import { PLACES, snapshot } from "./core";

export const qingganDays4To6 = [
  {
    dayNumber: 4,
    date: "2026-08-11",
    weekday: "周二",
    title: "莫高窟＋鸣沙山月牙泉",
    route: ["敦煌市区", "莫高窟", "酒店午休", "鸣沙山月牙泉"],
    transport: "市内打车",
    drivingKm: 0,
    intensity: "moderate",
    activities: [
      {
        id: "d4-mogao",
        startTime: "09:00",
        endTime: "12:00",
        name: "莫高窟A类票完整参观",
        description: "08:00—08:10从酒店出发，至少提前30分钟抵达数字展示中心。",
        place: PLACES.mogao,
        flexibility: "fixed",
        weatherProfile: "indoor",
        bookingStatus: "booked",
        fallbackSnapshot: snapshot("晴到多云", 16, 32, 15, 14, 35),
      },
      {
        id: "d4-rest",
        startTime: "13:30",
        endTime: "16:30",
        name: "酒店午休与高温避让",
        place: PLACES.dunhuang,
        flexibility: "fixed",
        weatherProfile: "indoor",
        fallbackSnapshot: snapshot("晴到多云", 16, 32, 15, 14, 35),
      },
      {
        id: "d4-mingsha",
        startTime: "17:20",
        endTime: "21:00",
        name: "鸣沙山骑骆驼、月牙泉与沙漠日落",
        place: PLACES.mingsha,
        flexibility: "movable",
        weatherProfile: "desert",
        bookingStatus: "pending",
        fallback: "风力过大时取消滑沙或骑骆驼，保留月牙泉和安全位置看日落。",
        fallbackSnapshot: snapshot("晴到多云", 16, 32, 15, 18, 32, { uvIndex: 8 }),
      },
    ],
    restaurants: [
      {
        name: "靖远尕六美味羊羔肉",
        meal: "lunch",
        recommendedDishes: ["白条羊羔肉", "清炖羊排", "沙葱炒蛋"],
        note: "午餐吃七分饱，避免影响午休。",
        priority: "primary",
      },
      {
        name: "沙洲市场附近胡羊焖饼店",
        meal: "lunch",
        recommendedDishes: ["胡羊焖饼", "凉菜", "杏皮水"],
        note: "选择有空调、可落座的正规餐厅。",
        priority: "backup",
      },
    ],
    hotel: { name: "敦煌飞天宾馆", location: "沙洲夜市附近", priceCny: 777.5, note: "连住第二晚" },
    planB: "鸣沙山遇大风时取消高风险体验，仅保留月牙泉与低强度日落观景。",
    executionNotes: ["午休不可取消", "老人不爬最高沙丘", "成人儿童与老人分组游览"],
  },
  {
    dayNumber: 5,
    date: "2026-08-12",
    weekday: "周三",
    title: "敦煌提车 → 当金山 → 翡翠湖 → 大柴旦",
    route: ["敦煌", "阿克塞", "当金山", "大柴旦翡翠湖", "大柴旦镇"],
    transport: "大众探岳自驾",
    drivingKm: 380,
    intensity: "moderate",
    activities: [
      {
        id: "d5-drive",
        startTime: "08:30",
        endTime: "15:00",
        name: "敦煌经当金山前往大柴旦",
        description: "不专程绕行U型公路、南八仙和G315网红机位。",
        place: PLACES.dachaidan,
        flexibility: "fixed",
        weatherProfile: "transit",
        latestDeparture: "08:30",
        fallbackSnapshot: snapshot("晴转局地阵雨", 13, 28, 35, 22, 55),
      },
      {
        id: "d5-emerald",
        startTime: "15:30",
        endTime: "18:00",
        name: "大柴旦翡翠湖",
        place: PLACES.emerald,
        flexibility: "movable",
        weatherProfile: "salt_lake",
        bookingStatus: "pending",
        fallback: "若16:30后才抵达，压缩为核心盐池路线；若雷雨持续，优先安全入住，不再等待光线。",
        fallbackSnapshot: snapshot("局地阵雨", 13, 28, 38, 14, 62),
      },
    ],
    restaurants: [
      {
        name: "来生缘牦牛土火锅·炕锅店",
        meal: "dinner",
        recommendedDishes: ["中份炕锅羊肉", "牦牛土火锅", "青菜"],
        note: "进入高海拔第一晚，少油少酒、七分饱。",
        priority: "primary",
      },
      {
        name: "伊布拉特色炕锅",
        meal: "dinner",
        recommendedDishes: ["炕锅羊肉", "汤面"],
        note: "首选排队或停业时切换。",
        priority: "backup",
      },
    ],
    hotel: { name: "大柴旦龍鑫淼酒店", location: "大柴旦镇中心", priceCny: 523, note: "大套间" },
    planB: "抵达翡翠湖晚于16:30时自动压缩游览；遇持续雷雨则直接入住，保证D6体力。",
    executionNotes: ["08:15可提早出发则不等待", "途中午餐控制30—40分钟", "晚上不饮酒、不安排夜游"],
  },
  {
    dayNumber: 6,
    date: "2026-08-13",
    weekday: "周四",
    title: "大柴旦 → 察尔汗盐湖 → 茶卡镇",
    route: ["大柴旦", "察尔汗盐湖", "诺木洪", "都兰", "茶卡镇"],
    transport: "大众探岳自驾",
    drivingKm: 580,
    intensity: "high",
    activities: [
      {
        id: "d6-drive-south",
        startTime: "06:40",
        endTime: "09:20",
        name: "大柴旦前往察尔汗游客中心",
        place: PLACES.qarhan,
        flexibility: "fixed",
        weatherProfile: "transit",
        latestDeparture: "06:40",
        fallbackSnapshot: snapshot("大部分晴", 12, 30, 15, 18, 32),
      },
      {
        id: "d6-qarhan",
        startTime: "09:20",
        endTime: "11:50",
        name: "察尔汗盐湖核心游览",
        description: "盐湖、彩色卤水、盐花及万丈盐桥相关景观合并游览。",
        place: PLACES.qarhan,
        flexibility: "movable",
        weatherProfile: "salt_lake",
        latestDeparture: "12:00",
        bookingStatus: "pending",
        fallback: "若排队导致11:30仍未进入核心区，缩短拍照点并确保12:00离开。",
        fallbackSnapshot: snapshot("大部分晴", 12, 30, 15, 17, 32),
      },
      {
        id: "d6-long-drive",
        startTime: "12:00",
        endTime: "20:30",
        name: "察尔汗前往茶卡镇",
        description: "中途至少休息2次，预计19:30—21:00到达。",
        place: PLACES.chaka,
        flexibility: "fixed",
        weatherProfile: "transit",
        latestDeparture: "12:00",
        fallback: "预计到达晚于21:30时不超速追回；D7自动压缩或取消茶卡盐湖。",
        fallbackSnapshot: snapshot("局地阵雨", 15, 27, 35, 20, 58),
      },
    ],
    restaurants: [
      {
        name: "西遇舌尖牦牛火锅美食城",
        meal: "dinner",
        recommendedDishes: ["小份牦牛火锅", "蔬菜", "面条"],
        note: "长途驾驶后以热汤和易消化食物为主，提前确认最晚点餐。",
        priority: "primary",
      },
      {
        name: "瀚海丝路风情餐厅",
        meal: "dinner",
        recommendedDishes: ["茶卡贡羊", "西北热菜", "汤面"],
        note: "到达较晚时优先选择营业时间更稳定的酒店餐饮。",
        priority: "backup",
      },
    ],
    hotel: { name: "怀希酒店（茶卡店）", location: "茶卡镇中心", priceCny: 740 },
    planB:
      "D6抵达茶卡晚于21:00或全家明显疲劳时，D7茶卡改为快速游或直接取消，优先青海湖与准时还车。",
    executionNotes: [
      "建议两位成人轮换驾驶",
      "12:00必须离开察尔汗",
      "万丈盐桥不单独导航",
      "当晚不游茶卡",
    ],
  },
] satisfies ReadonlyArray<TripDay>;
