import type { TripDay } from "../types";
import { PLACES, snapshot } from "./core";

export const qingganDays1To3 = [
  {
    dayNumber: 1,
    date: "2026-08-08",
    weekday: "周六",
    title: "福州 → 兰州中川机场",
    route: ["福州", "兰州中川机场"],
    transport: "飞机＋酒店接驳",
    drivingKm: 0,
    intensity: "easy",
    activities: [
      {
        id: "d1-flight",
        startTime: "17:15",
        endTime: "20:30",
        name: "厦门航空福州飞兰州",
        description: "15:00抵达长乐机场，落地后直接入住机场酒店。",
        place: PLACES.lanzhouAirport,
        flexibility: "fixed",
        weatherProfile: "transit",
        bookingStatus: "booked",
        fallback: "航班延误时取消宵夜，优先完成酒店接驳与休息。",
        fallbackSnapshot: snapshot("晴", 14, 29, 10, 12, 25),
      },
      {
        id: "d1-supper",
        startTime: "21:20",
        endTime: "22:00",
        name: "机场附近简单宵夜",
        place: PLACES.lanzhouAirport,
        flexibility: "movable",
        weatherProfile: "city_night",
        fallback: "若抵达较晚，直接在酒店餐厅或房间内简单用餐。",
        fallbackSnapshot: snapshot("晴", 14, 29, 10, 12, 25),
      },
    ],
    restaurants: [
      {
        name: "佰翔酒店餐厅或附近牛肉面馆",
        meal: "dinner",
        recommendedDishes: ["兰州牛肉面", "灰豆子", "牛奶鸡蛋醪糟"],
        note: "抵达较晚，优先选择仍营业且步行可达的餐厅。",
        priority: "primary",
      },
    ],
    hotel: { name: "兰州中川机场佰翔酒店", location: "中川机场附近", priceCny: 476 },
    planB: "若航班延误，取消宵夜，落地后直接入住并准备次日早班城际。",
    executionNotes: ["薄外套随身携带", "酒店接驳时间提前确认"],
  },
  {
    dayNumber: 2,
    date: "2026-08-09",
    weekday: "周日",
    title: "兰州 → 张掖 → 七彩丹霞日落",
    route: ["中川机场站", "兰州西", "张掖西", "七彩丹霞", "张掖市区"],
    transport: "城际＋高铁＋威兰达自驾",
    drivingKm: 90,
    intensity: "moderate",
    activities: [
      {
        id: "d2-rail",
        startTime: "07:02",
        endTime: "11:10",
        name: "中川机场站经兰州西前往张掖西",
        description: "兰州西站换乘47分钟，使用站内便捷换乘。",
        place: PLACES.zhangye,
        flexibility: "fixed",
        weatherProfile: "transit",
        bookingStatus: "booked",
        fallbackSnapshot: snapshot("晴", 20, 38, 5, 15, 18),
      },
      {
        id: "d2-car-pickup",
        startTime: "11:30",
        endTime: "12:00",
        name: "张掖西站取威兰达",
        place: PLACES.zhangye,
        flexibility: "fixed",
        weatherProfile: "transit",
        bookingStatus: "booked",
        fallbackSnapshot: snapshot("晴", 20, 38, 5, 15, 18),
      },
      {
        id: "d2-danxia",
        startTime: "15:00",
        endTime: "20:00",
        name: "七彩丹霞完整游览与日落",
        place: PLACES.danxia,
        flexibility: "movable",
        weatherProfile: "sunset",
        latestDeparture: "20:10",
        bookingStatus: "pending",
        fallback: "若下午持续强降雨，先游张掖大佛寺；雨势减弱后再决定是否进入丹霞。",
        fallbackSnapshot: snapshot("晴", 20, 38, 5, 16, 28, { uvIndex: 11 }),
      },
    ],
    restaurants: [
      {
        name: "甘州名吃",
        meal: "lunch",
        recommendedDishes: ["搓鱼子", "羊肉垫卷子", "沙葱炒蛋"],
        note: "适合5人分享，午餐控制七分饱。",
        priority: "primary",
      },
      {
        name: "孙记炒炮（西街店）",
        meal: "lunch",
        recommendedDishes: ["炒炮", "卤排骨", "酱牛肉"],
        note: "首选排队过长时切换。",
        priority: "backup",
      },
    ],
    hotel: { name: "张掖西站御景国际酒店", location: "张掖西站附近", priceCny: 696 },
    planB: "丹霞遇持续降雨时，改游张掖大佛寺；若只是短时阵雨，延后入园并保留日落窗口。",
    executionNotes: ["高温日每人至少准备1升水", "老人减少登高观景台", "日落后夜间返城谨慎驾驶"],
  },
  {
    dayNumber: 3,
    date: "2026-08-10",
    weekday: "周一",
    title: "马蹄寺 → 敦煌",
    route: ["张掖市区", "马蹄寺", "张掖市区还车", "张掖西", "敦煌"],
    transport: "威兰达自驾＋高铁",
    drivingKm: 135,
    intensity: "moderate",
    activities: [
      {
        id: "d3-mati",
        startTime: "08:00",
        endTime: "10:30",
        name: "马蹄寺精华游",
        description: "老人以寺院、山谷与石窟外观为主，三十三天石窟按体力分组。",
        place: PLACES.mati,
        flexibility: "movable",
        weatherProfile: "mountain",
        latestDeparture: "10:30",
        bookingStatus: "pending",
        fallback: "若山区降雨、老人腿脚不适或睡眠不足，改为张掖大佛寺＋市区轻松游。",
        fallbackSnapshot: snapshot("晴", 16, 32, 15, 14, 30),
      },
      {
        id: "d3-train",
        startTime: "15:16",
        endTime: "19:26",
        name: "张掖西高铁前往敦煌",
        place: PLACES.dunhuang,
        flexibility: "fixed",
        weatherProfile: "transit",
        bookingStatus: "booked",
        fallbackSnapshot: snapshot("晴", 21, 37, 5, 15, 18),
      },
      {
        id: "d3-night-market",
        startTime: "20:10",
        endTime: "21:20",
        name: "敦煌正式晚餐与沙洲夜市",
        place: PLACES.dunhuang,
        flexibility: "movable",
        weatherProfile: "city_night",
        fallback: "高铁晚点时只吃正式晚餐，取消夜市闲逛。",
        fallbackSnapshot: snapshot("晴", 21, 37, 5, 12, 18),
      },
    ],
    restaurants: [
      {
        name: "五味香·驴肉黄面·胡杨焖饼",
        meal: "dinner",
        recommendedDishes: ["驴肉黄面", "胡羊焖饼", "杏皮水"],
        note: "先坐下吃正式晚餐，再少量逛夜市。",
        priority: "primary",
      },
      {
        name: "天外天驴肉黄面胡杨焖饼",
        meal: "dinner",
        recommendedDishes: ["驴肉黄面", "胡杨焖饼"],
        note: "首选等位过长时切换。",
        priority: "backup",
      },
    ],
    hotel: {
      name: "敦煌飞天宾馆",
      location: "沙洲夜市步行约5分钟",
      priceCny: 777.5,
      note: "两晚合计1555元",
    },
    planB: "马蹄寺天气或体力不佳时改张掖大佛寺，保证15:16高铁绝不受影响。",
    executionNotes: ["10:30无条件离开马蹄寺", "11:45前回城加油还车", "14:00左右抵达张掖西站"],
  },
] satisfies ReadonlyArray<TripDay>;
