import type { TripDay } from "../types";
import { PLACES, snapshot } from "./core";

export const qingganDays7To9 = [
  {
        dayNumber: 7,
        date: "2026-08-14",
        weekday: "周五",
        title: "茶卡盐湖 → 黑马河 → 青海湖 → 西宁",
        route: ["茶卡镇", "茶卡盐湖", "黑马河", "青海湖环湖西路", "西宁"],
        transport: "大众探岳自驾",
        drivingKm: 300,
        intensity: "high",
        activities: [
          {
            id: "d7-chaka",
            startTime: "07:20",
            endTime: "08:50",
            name: "茶卡盐湖首批游览",
            place: PLACES.chaka,
            flexibility: "movable",
            weatherProfile: "salt_lake",
            latestDeparture: "09:10",
            bookingStatus: "pending",
            fallback: "风大或持续降雨时压缩为50分钟，或直接取消并提前前往青海湖。",
            fallbackSnapshot: snapshot("间歇性降雨", 11, 24, 55, 18, 72),
          },
          {
            id: "d7-qinghai",
            startTime: "10:30",
            endTime: "13:00",
            name: "黑马河与青海湖环湖西路精华段",
            place: PLACES.qinghaiLake,
            flexibility: "movable",
            weatherProfile: "lake",
            latestDeparture: "13:20",
            fallback: "午后降雨提前时，只保留一个正规观景点并提前前往西宁。",
            fallbackSnapshot: snapshot("下午小雨", 8, 20, 48, 22, 68),
          },
          {
            id: "d7-return",
            startTime: "13:20",
            endTime: "17:30",
            name: "青海湖前往西宁并还车",
            place: PLACES.xining,
            flexibility: "fixed",
            weatherProfile: "transit",
            latestDeparture: "13:30",
            bookingStatus: "booked",
            fallbackSnapshot: snapshot("多云", 12, 26, 30, 16, 55),
          },
        ],
        restaurants: [
          {
            name: "清真尕穆萨美食城总店",
            meal: "dinner",
            recommendedDishes: ["手抓羊肉", "黄焖羊肉", "尕面片"],
            note: "若还车较晚或全家疲劳，可改为酒店附近简餐。",
            priority: "primary",
          },
          {
            name: "益鑫羊肉手抓馆",
            meal: "dinner",
            recommendedDishes: ["手抓羊肉", "羊肉汤", "老酸奶"],
            note: "不逛夜市时的舒适备选。",
            priority: "backup",
          },
          {
            name: "德禄酸奶（莫家街店）",
            meal: "snack",
            recommendedDishes: ["原味老酸奶", "甜醅"],
            note: "只作为甜品补充。",
            priority: "primary",
          },
        ],
        hotel: { name: "西宁伊尔顿国际饭店", location: "西宁站附近", priceCny: 840 },
        planB: "天气好的青海湖优先于风雨中的茶卡；茶卡评分低时直接缩短，确保13:30前离开青海湖并按时还车。",
        executionNotes: ["前一晚确认逐小时风力", "一次性雨衣优于雨伞", "提前确认还车门店最晚时间"],
      },
  {
        dayNumber: 8,
        date: "2026-08-15",
        weekday: "周六",
        title: "西宁 → 塔尔寺 → 兰州 → 甘肃省博物馆 → 黄河夜景",
        route: ["西宁", "塔尔寺", "西宁站", "兰州西", "甘肃省博物馆", "中山桥"],
        transport: "打车＋高铁",
        drivingKm: 0,
        intensity: "moderate",
        activities: [
          {
            id: "d8-kumbum",
            startTime: "08:15",
            endTime: "09:45",
            name: "塔尔寺精华游",
            place: PLACES.kumbum,
            flexibility: "movable",
            weatherProfile: "mountain",
            latestDeparture: "09:45",
            bookingStatus: "pending",
            fallback: "持续降雨时缩短为60分钟，优先保证高铁和甘肃省博物馆。",
            fallbackSnapshot: snapshot("间歇性降雨", 18, 26, 50, 16, 70),
          },
          {
            id: "d8-rail",
            startTime: "13:00",
            endTime: "14:02",
            name: "西宁高铁前往兰州西",
            place: PLACES.lanzhou,
            flexibility: "fixed",
            weatherProfile: "transit",
            bookingStatus: "booked",
            fallbackSnapshot: snapshot("多云", 17, 30, 25, 14, 58),
          },
          {
            id: "d8-museum",
            startTime: "14:45",
            endTime: "17:00",
            name: "甘肃省博物馆",
            description: "抵达兰州后先到酒店寄存行李，16:30前必须完成入馆。",
            place: PLACES.lanzhou,
            flexibility: "fixed",
            weatherProfile: "indoor",
            latestDeparture: "17:00",
            bookingStatus: "pending",
            fallbackSnapshot: snapshot("多云", 17, 30, 25, 14, 58),
          },
          {
            id: "d8-night",
            startTime: "18:30",
            endTime: "21:15",
            name: "正式晚餐、中山桥与黄河风情线",
            place: PLACES.lanzhou,
            flexibility: "movable",
            weatherProfile: "city_night",
            fallback: "降雨时取消河边长距离步行，仅保留正式晚餐和近距离夜景。",
            fallbackSnapshot: snapshot("多云", 17, 30, 30, 15, 65),
          },
        ],
        restaurants: [
          {
            name: "阿西娅·西北妈妈拿手菜（西站店）",
            meal: "dinner",
            recommendedDishes: ["手抓羊肉", "黄焖羊肉", "酿皮"],
            note: "先吃正式晚餐，再前往黄河夜景。",
            priority: "primary",
          },
          {
            name: "忠华手抓大王（硷沟沿店）",
            meal: "dinner",
            recommendedDishes: ["手抓羊肉", "西北热菜", "汤面"],
            note: "甘肃省博物馆附近备选。",
            priority: "backup",
          },
          {
            name: "正宁路夜市",
            meal: "snack",
            recommendedDishes: ["牛奶鸡蛋醪糟", "灰豆子", "甜醅子"],
            note: "只作为甜品或小吃补充，不作为正式晚餐。",
            priority: "primary",
          },
        ],
        hotel: {
          name: "兰州西站西津西路亚朵酒店",
          location: "兰州西站附近",
          priceCny: 984,
          note: "发票需包含全部入住人及入住、离店日期",
        },
        planB: "塔尔寺遇雨缩短，固定高铁与博物馆优先；兰州夜间降雨时取消长距离河边步行。",
        executionNotes: ["09:45离开塔尔寺", "兰州先寄存行李再去甘博", "正宁路不作为正式晚餐"],
      },
  {
        dayNumber: 9,
        date: "2026-08-16",
        weekday: "周日",
        title: "兰州 → 福州",
        route: ["兰州西站", "中川机场", "福州"],
        transport: "城际铁路＋飞机",
        drivingKm: 0,
        intensity: "easy",
        activities: [
          {
            id: "d9-airport-rail",
            startTime: "08:32",
            endTime: "09:16",
            name: "兰州西站城际前往中川机场",
            place: PLACES.lanzhouAirport,
            flexibility: "fixed",
            weatherProfile: "transit",
            bookingStatus: "booked",
            fallbackSnapshot: snapshot("部分晴", 16, 28, 25, 15, 45),
          },
          {
            id: "d9-flight",
            startTime: "11:25",
            endTime: "14:35",
            name: "厦门航空返回福州",
            place: PLACES.lanzhouAirport,
            flexibility: "fixed",
            weatherProfile: "transit",
            bookingStatus: "booked",
            fallback: "如航班延误，使用随身零食并关注登机口变化。",
            fallbackSnapshot: snapshot("部分晴", 16, 28, 25, 15, 45),
          },
        ],
        restaurants: [
          {
            name: "亚朵酒店早餐",
            meal: "breakfast",
            recommendedDishes: ["热粥", "鸡蛋", "面点", "水果"],
            note: "07:00开始早餐，不外出寻找牛肉面。",
            priority: "primary",
          },
        ],
        planB: "城际或航班异常时优先关注官方通知，不临时改乘远距离公路交通。",
        executionNotes: ["07:25前退房", "08:00前完成进站", "儿童零食与常温奶随身携带"],
      }
] satisfies ReadonlyArray<TripDay>;
