name = "where-not-rain-read"
compatibility_date = "2025-07-01"
main = "./dist/index.js"

[[d1_databases]]
binding = "DB"
database_name = "wnr-weather"
database_id = "c822f407-c62c-438c-94f6-345a57122827"

[env.preview]
vars = { WEB_ORIGIN = "https://where-not-rain.pages.dev" }

[[env.preview.d1_databases]]
binding = "DB"
database_name = "wnr-weather-preview"
database_id = "2f3b76f0-e0e2-4a5a-bcb5-c4b233c56afe"

[env.production]
vars = { WEB_ORIGIN = "https://where-not-rain.pages.dev" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "wnr-weather"
database_id = "c822f407-c62c-438c-94f6-345a57122827"
