// Generated by Wrangler by running `wrangler types --env production`

interface Env {
	WEB_ORIGIN: "http://localhost:3000" | "https://where-not-rain.pages.dev" | "https://868656.xyz";
	PRODUCT_EVENTS: AnalyticsEngineDataset;
}
